disallowed-types = [
    { path = "std::collections::HashSet", reason = "use pumpkin_solver::core::containers::HashSet" },
    { path = "std::collections::HashMap", reason = "use pumpkin_solver::core::containers::HashMap" },
    { path = "rand::Rng", reason = "use pumpkin_solver::basic_types::Random" },
    { path = "rand::RngExt", reason = "use pumpkin_solver::basic_types::Random" },
    { path = "rand::SeedableRng", reason = "use pumpkin_solver::basic_types::Random" },
]

allowed-duplicate-crates = [
    "wit-bindgen",
    "hashbrown",
]
