on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Release Please

jobs:
  handle-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        id: release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Update README
        if: ${{ steps.release-please.outputs.pr != null }}
        run: echo ${{ steps.release-please.outputs.pr }}
        
