name: Validate .msc files 

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Validate JSON files
        run: |
          set -eux

          json_pp -t null < minizinc/pumpkin.msc
          json_pp -t null < minizinc/pumpkin-for-proofs.msc
